spring:
  application:
    name: datahub

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    username: dev
    password: abc123
    driver-class-name: org.postgresql.Driver

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
server:
  port: 8280
  servlet:
    context-path: "/data-hub"
